### ISSUE TITLE
When in edit mode form is not loading.

### ISSUE THREAD

**Issue by lvdhoorn** [dcasia/conditional-container#11] opened 2019-11-15 16:29 UTC
When you use the ConditionalContainer while editing a resource the edit page won't load anymore if the condition matches. If the conditions don't match the page is loading normal.

```
Select::make('Invoice Period', 'invoice_period')
->options(['never' => 'Never', 'ten_days'  => 'Ten days', 'monthly' => 'Monthly'])
->sortable()
->displayUsingLabels()
->rules('required'),
ConditionalContainer::make([Text::make('Description', 'description')
->hideFromIndex()])
->if('invoice_period = ten_days OR invoice_period = monthly')
```

So if the resource loads with invoice_period never the page will load normal if the resource loads with the invoice_period on ten_days or monthly the page won't load.

**Comment by milewski** [comment] 2019-11-16 03:59
@lvdhoorn maybe you forgot to import the `HasConditionalContainer` trait?

**Comment by milewski** [comment] 2019-11-16 12:56
I have just copied and pasted your code on a fresh nova install and everything seems to work, perhaps the issue lies with some other field you may be using? im closing for now but feel free to comment giving more information in case the issue is with this package thanks.

**Closed by milewski** 2019-11-16 12:56 UTC

**Comment by lvdhoorn** [comment] 2019-11-18 22:52
Hi Milewski,

i think i found the problem. If the ConditionalContainer is inside a tabs package it is not working. We use the  https://github.com/eminiarts/nova-tabs package. Without the tabs the ConditionalContainer is working fine. Other packages are working inside the tabs.
